name: pr-name-linter
on:
  pull_request:
    types: ['opened', 'edited', 'reopened', 'synchronize']

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Install Dependencies
        run: npm install @commitlint/config-conventional
      - name: Lint PR name
        uses: JulienKode/pull-request-name-linter-action@v0.5.0
